name: Exemplo output
run-name: Exemplo workflow output, executado por ${{ github.actor }} #nome ao ser executar o workflow
on:
  workflow_dispatch:
jobs:
  gerando_output:
    runs-on: ubuntu-latest
    outputs:  # criação dos outputs a nivel de job
      output-shell: ${{ steps.exemplo-output.outputs.action_random }}
      output-generatedpassword: ${{ steps.generatedpassword.outputs.password }}
    steps:
      - name: Gerando output com shell
        id: exemplo-output # deve ser criado para servir como referencia
        run: |
          ACTION_RANDOM=$(( $RANDOM )) 
          echo "action_random=$ACTION_RANDOM" >> $GITHUB_OUTPUT 
      
      - name: Exibindo o output
        run: echo "${{ steps.exemplo-output.outputs.action_random}}" # coleta do resultado do output
      
      - name: Gerador de senha
        id: generatedpassword
        uses: aammirmirza/RandomPasswordGenerator@v1.1
        with:
          length: 15
      
      - name: Exibindo o output da action de password
        run: echo "${{steps.generatedpassword.outputs.password}}"
  
  exibindo_valores:
    needs: [gerando_output]  # o jobs deve ser dependente do job que contem os outputs
    runs-on: ubuntu-latest
    steps:
      - name: Exibindo os outputs do gerando_outpus
        run: |
          echo "output shell: ${{ needs.gerando_output.outputs.output-shell }}"
          echo "output password: ${{ needs.gerando_output.outputs.output-generatedpassword }}"

