name: Exemplo output
run-name: Exemplo workflow output, executado por ${{ github.actor }} #nome ao ser executar o workflow
on:
  workflow_dispatch:
jobs:
  gerando_output:
    runs-on: ubuntu-latest
    steps:
      - name: Gerando output com shell
        id: exemplo-output # deve ser criado para servir como referencia
        run: |
          ACTION_RANDOM=$(( $RANDOM )) 
          echo "action_random=$ACTION_RANDOM" >> $GITHUB_OUTPUT 
      
      - name: Exibindo o output
        run: echo "${{ steps.exemplo-output.outputs.action_random}}" # coleta do resultado do output
      
      - name: Gerador de senha
        id: generatedpassword
        uses: aammirmirza/RandomPasswordGenerator@v1.1
        with:
          length: 15
      
      - name: Exibindo o output da action de password
        run: echo "${{steps.generatedpassword.outputs.password}}"

