name: Exemplo input
run-name: Exemplo workflow input, executado por ${{ github.actor }} #nome ao ser executar o workflow
on:
  workflow_dispatch:
    inputs:  # dados inseridos pelo usuario
      versao: 
        type: string                            # tipo
        required: true                          # obrigatoriedade
        default: "dev"                          # valor padrão 
        description: "Versão: V1.0"    # descrição
      numero_card:
        type: number
        required: true
        description: "Número: 1.0"
      fazer_deploy:
        type: boolean
        required: true
        description: "Especifica se deve ou não fazer deploy"
      ambiente:
        type: choice
        required: true
        description: "Ambiente de deploy"
        options:
          - Desenvolvimento
          - Homologação
          - Produção
jobs:
  valores_input:
    runs-on: ubuntu-latest
    steps:
      - name: Exibindo o contexto de input completo
        run: echo "${{toJson(inputs)}}"       # contexto que exibe informações sobre os inputs
      - name: Exibindo os valores individualmente
        run: |
          echo "Valores do inputs"
          echo "A versão é: ${{inputs.versao}}"
          echo "O card é: ${{inputs.numero_card}}"
          echo "Deve fazer deploy: ${{inputs.fazer_deploy}}"
          echo "O ambiente é: ${{inputs.ambiente}}"

